FROM occlum/occlum:0.22.0-ubuntu18.04
COPY files/aesmd.conf /etc/aesmd.conf
COPY files/msprod.list /etc/apt/sources.list.d/msprod.list
RUN wget -qO - https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
COPY files/setup-build.sh /
RUN bash /setup-build.sh
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
